name:                dziwqrim-dict-conv
version:             0.1.0.0
github:              "na4zagin3/dziwqrim-dict-conv"
license:             BSD3
author:              "Noriaki Sakamoto"
maintainer:          "mrty.ityt.pt@gmail.com"
copyright:           "2022 Noriaki Sakamoto"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/na4zagin3/dziwqrim-dict-conv#readme>

dependencies:
- base >= 4.7 && < 5
# Datatypes
- containers
- nonempty-vector
- transformers
- vector
# String
- bytestring
- text
# CSV
- cassava > 0.5 && < 0.6
# TeX
- HaTeX
# QR Code
- qrcode-core
# Parsing
- attoparsec

library:
  source-dirs: src

executables:
  dziwqrim-dict-conv-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dziwqrim-dict-conv

tests:
  dziwqrim-dict-conv-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dziwqrim-dict-conv
    - doctest
